Clean up Travis script

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,51 +1,44 @@
 language: objective-c
 osx_image: xcode8.3
+
 branches:
   only:
     - master
+
 env:
   global:
-  - LC_CTYPE=en_US.UTF-8
-  - LANG=en_US.UTF-8
-  - WORKSPACE=Telegraph.xcworkspace
-  - IOS_FRAMEWORK_SCHEME="Telegraph iOS"
-  - MACOS_FRAMEWORK_SCHEME="Telegraph macOS"
-  - TVOS_FRAMEWORK_SCHEME="Telegraph tvOS"
-  - EXAMPLE_SCHEME="iOS Example"
+    - LANG=en_US.UTF-8
+    - LC_CTYPE=en_US.UTF-8
+    - WORKSPACE=Telegraph.xcworkspace
   matrix:
-    - DESTINATION="OS=10.3.1,name=iPhone 7 Plus"   SCHEME="$IOS_FRAMEWORK_SCHEME"      RUN_TESTS="YES" BUILD_EXAMPLE="NO" POD_LINT="NO"
-    - DESTINATION="OS=9.0,name=iPad Air"           SCHEME="$IOS_FRAMEWORK_SCHEME"      RUN_TESTS="NO" BUILD_EXAMPLE="NO" POD_LINT="NO"
+    # Latest devices
+    - DESTINATION="platform=iOS Simulator,name=iPhone 7 Plus"           SCHEME="Telegraph iOS"      RUN_TESTS="YES"
+    - DESTINATION="platform=iOS Simulator,name=iPad Pro (12.9-inch)"    SCHEME="Telegraph iOS"      RUN_TESTS="NO"
+    - DESTINATION="platform=tvOS Simulator,name=Apple TV 1080p"         SCHEME="Telegraph tvOS"     RUN_TESTS="NO"
+    - DESTINATION="platform=macOS,arch=x86_64"                          SCHEME="Telegraph macOS"    RUN_TESTS="NO"
 
-    - DESTINATION="OS=10.2,name=Apple TV 1080p"    SCHEME="$TVOS_FRAMEWORK_SCHEME"     RUN_TESTS="NO" BUILD_EXAMPLE="NO"  POD_LINT="NO"
+    # Older devices
+    - DESTINATION="platform=iOS Simulator,name=iPad 2,OS=9.0"           SCHEME="Telegraph iOS"      RUN_TESTS="YES"
+    - DESTINATION="platform=iOS Simulator,name=iPhone 5s,OS=9.0"        SCHEME="Telegraph iOS"      RUN_TESTS="NO"
 
-    - DESTINATION="arch=x86_64"                    SCHEME="$MACOS_FRAMEWORK_SCHEME"    RUN_TESTS="NO" BUILD_EXAMPLE="NO"  POD_LINT="NO"
 before_install:
-  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
-script:
-  - set -o pipefail
+  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
+  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
+  - pod --version
   - xcodebuild -version
   - xcodebuild -showsdks
 
-  # Build Framework in Debug and Run Tests if specified
+script:
+  # Produce a failure return code if any command errors
+  - set -o pipefail
+
+  # Build in Debug mode
+  - xcodebuild clean build -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO | xcpretty -c;
+
+  # Build in Release mode
+  - xcodebuild clean build -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO | xcpretty -c;
+
+  # Run the tests
   - if [ $RUN_TESTS == "YES" ]; then
-      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty;
-    else
-      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty;
-    fi
-
-  # Build Framework in Release and Run Tests if specified
-  - if [ $RUN_TESTS == "YES" ]; then
-      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty;
-    else
-      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty;
-    fi
-
-  # Build Example in Debug if specified
-  - if [ $BUILD_EXAMPLE == "YES" ]; then
-      xcodebuild -workspace "$WORKSPACE" -scheme "$EXAMPLE_SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty;
-    fi
-
-  # Run `pod lib lint` if specified
-  - if [ $POD_LINT == "YES" ]; then
-      pod lib lint;
+      xcodebuild test -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES | xcpretty -c;
     fi
